name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-Debug-Version:
    runs-on: ubuntu-latest
    environment: BUILD
    container:
      image: androidsdk/android-33
    steps:
      - uses: actions/checkout@v3

      - name: Permission Gradle
        run: chmod +x ./gradlew

      - name: Version Debug
        run: ./gradlew build

      - name: Upload Apk Debug
        uses: actions/upload-artifact@v3
        with:
          name: debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  build-Release-Version:
    needs:
      - build-Debug-Version
    runs-on: ubuntu-latest
    environment: RELEASE
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3

      - name: Permission Gradle
        run: chmod +x ./gradlew

      - name: Release Version
        run: ./gradlew assembleRelease

      - name: Upload Apk Release
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: app/build/outputs/apk/release/app-release.apk
  Alpha-PlayStore:
    needs:
      - build-Release-Version
    runs-on: ubuntu-latest
    environment: PLAYSTORE
    container:
      image: androidsdk/android-30
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        env:
          KEYSTORE_APP: ${{secrets.KEYSTORE}}
          SERVICE_ACCOUNT_APP: ${{secrets.SERVICE_ACCOUNT}}
        run: |
          echo $KEYSTORE_APP | base64 -d > app/chat_keystore.jks
          echo $SERVICE_ACCOUNT_APP | base64 -d > app/service_account_play_console.json

      - name: Deploy Alpha PlayStore
        run: |
          ./gradlew assembleRelease
          ./gradlew promoteArtifact --promote-track alpha